name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions: {}

concurrency:
  group: rebar3-grisp-io-saas-tests
  cancel-in-progress: false

jobs:
  ci:
    runs-on: ubuntu-24.04
    name: Erlang ${{matrix.otp}} / rebar ${{matrix.rebar3}}
    permissions:
      contents: read
    strategy:
      max-parallel: 1
      matrix:
        otp: ['28', '29']
        rebar3: ['3']
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Compile
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 compile

      - name: Dialyzer
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 dialyzer

      - name: Common test
        env:
          GRISP_CI_DEVICE: ${{ secrets.GRISP_CI_DEVICE }}
          GRISP_CI_PASSWORD: ${{ secrets.GRISP_CI_PASSWORD }}
          GRISP_CI_USERNAME: ${{ secrets.GRISP_CI_USERNAME }}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 ct
