name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-20.04
    name: Erlang ${{matrix.otp}} / rebar ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['25', '26', '27']
        rebar3: ['3']
    steps:

      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Compile
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 compile

      - name: Dialyzer
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 dialyzer

      - name: Common test
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STRITZINGER_BOT_SSH_KEY }}'
          rebar3 ct
